# Generated by Django 4.0.3 on 2022-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_withdrawals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawals',
            name='current_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Successful', 'Successful')], default='Pending', max_length=50),
        ),
    ]
