# Generated by Django 4.0.3 on 2022-04-05 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0005_alter_withdrawals_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
