# Generated by Django 4.0.3 on 2022-04-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_alter_withdrawals_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawals',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
    ]
