# Generated by Django 4.0.3 on 2022-04-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Level 0', 'Level 0'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8')], max_length=50)),
                ('down_lines', models.IntegerField(blank=True)),
                ('referral_bonus', models.IntegerField(blank=True)),
                ('match_bonus', models.IntegerField(blank=True)),
                ('upgrade_payment', models.IntegerField(blank=True)),
                ('reward', models.TextField(blank=True)),
            ],
        ),
    ]
