# Generated by Django 4.0.3 on 2022-04-07 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0011_level_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='user',
        ),
        migrations.CreateModel(
            name='CurrentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
