# Generated by Django 4.0.3 on 2022-04-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='local_government',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
