# Generated by Django 4.0.3 on 2022-04-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_alter_withdrawals_options_alter_profile_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated',
        ),
    ]
