# Generated by Django 4.0.3 on 2022-04-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_remove_profile_created_remove_profile_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='down_lines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='match_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='referral_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='reward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='upgrade_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
