# Generated by Django 4.0.3 on 2022-04-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_companyinformation_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='pic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
