# Generated by Django 4.0.3 on 2022-04-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_howwework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='message',
            new_name='testimony',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='location',
            field=models.CharField(default='Abuja', max_length=15),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Sam', max_length=50),
        ),
    ]
