# Generated by Django 4.0.3 on 2022-04-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_rename_message_testimonial_testimony_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=15)),
                ('testimony', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
