# Generated by Django 4.0.3 on 2022-04-24 06:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_alter_alltestimonial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howwework',
            name='pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
