# Generated by Django 4.0.3 on 2022-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_alter_alltestimonial_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
