# Generated by Django 4.0.3 on 2022-05-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_emailsubscription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corevalue',
            name='pic',
        ),
        migrations.AddField(
            model_name='corevalue',
            name='font_awesome_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
