# Generated by Django 4.0.3 on 2022-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0014_remove_corevalue_pic_corevalue_font_awesome_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhoWeAre',
            new_name='NetworkMarketing',
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
