# Generated by Django 4.0.3 on 2022-05-05 14:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_rename_whoweare_networkmarketing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='history_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
