# Generated by Django 4.0.3 on 2022-05-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0016_companyinformation_history_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
