# Generated by Django 4.0.3 on 2022-05-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0018_alter_alltestimonial_testimony_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkMarketing',
            new_name='OtherWebPages',
        ),
    ]
