# Generated by Django 4.0.3 on 2022-05-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_rename_networkmarketing_otherwebpages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact_one', models.CharField(max_length=11)),
                ('contact_two', models.CharField(blank=True, max_length=11, null=True)),
                ('contact_three', models.CharField(blank=True, max_length=11, null=True)),
                ('contact_four', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='companyinformation',
            options={'verbose_name_plural': 'Company Information'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='heromenu',
            options={'verbose_name_plural': 'Hero Menu'},
        ),
        migrations.AlterModelOptions(
            name='howwework',
            options={'verbose_name_plural': 'How We Work'},
        ),
        migrations.AlterModelOptions(
            name='otherwebpages',
            options={'verbose_name_plural': 'Other Web Pages'},
        ),
        migrations.AlterModelOptions(
            name='photogallery',
            options={'verbose_name_plural': 'Photo Gallery'},
        ),
    ]
