# Generated by Django 4.0.3 on 2022-05-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0020_branchaddress_alter_companyinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchaddress',
            options={'verbose_name_plural': 'Branch Addresses'},
        ),
    ]
