# Generated by Django 4.0.3 on 2022-05-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0023_contactus_phone_number_contactus_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
