# Generated by Django 4.0.3 on 2022-05-29 06:41

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0024_rename_phone_number_contactus_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=50)),
                ('snippet', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Network Marketing',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('snippet', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('snippet', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Terms And Conditions',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('snippet', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us',
            },
        ),
    ]
