# Generated by Django 4.0.3 on 2022-05-29 07:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0025_networkmarketing_privacypolicy_termsandconditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
