# Generated by Django 4.0.3 on 2022-05-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0026_whychooseus_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
