# Generated by Django 4.0.3 on 2022-05-29 07:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0027_whychooseus_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='page_header_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='networkmarketing',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
