# Generated by Django 4.0.3 on 2022-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0029_alter_companyinformation_page_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_awesome_class', models.CharField(max_length=30)),
                ('stat_figure', models.IntegerField()),
                ('stat_title', models.CharField(max_length=50)),
            ],
        ),
    ]
