# Generated by Django 4.0.3 on 2022-07-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0030_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_awesome_class', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='linkenin_url',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='whataspp_url',
        ),
    ]
